library(shiny)
library(tidyverse)


ui <- fluidPage(
  
  # Sidebar with an input for column
  # boolean input
  # and value input
  sidebarLayout(
    sidebarPanel(
      fluidRow(column(4, selectInput("COLUMN", "Filter By:", choices = colnames(iris))),
               column(4, selectInput("CONDITION", "Boolean", choices = c("==", "!=", ">", "<"))),
               column(4, uiOutput("COL_VALUE")))
    ),
    
    # Show text generated by sidebar
    # use text in tidy pipeline to create subsetted dataframe
    mainPanel(
      verbatimTextOutput("as_text"),
      tableOutput("the_data")
    )
  )
)

# Define server logic required to draw a histogram
server <- function(input, output) {
  
  output$COL_VALUE <- renderUI({
    x <- iris %>% select(!!sym(input$COLUMN))
    selectInput("VALUE", "Value", choices = x, selected = x[1])
  })
  
  filtering_string <- reactive ({
    paste0("filter(iris, ", input$COLUMN, " ", input$CONDITION, " ", input$VALUE, ")")
  })
  
  output$as_text <- renderText({
    filtering_string()
  })
  
  
  output$the_data <- renderTable({
    eval(parse(text = filtering_string()))
  })
}

# Run the application 
shinyApp(ui = ui, server = server)